name: infra-kit

services:
  postgres:
    image: postgres:16-alpine
    container_name: infra_kit_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: infra_kit_rabbitmq
    profiles: ["mq"]
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: infra_kit_redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer:4
    container_name: infra_kit_adminer
    profiles: ["adminer"]
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: infra_kit_pgadmin
    profiles: ["pgadmin"]
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
      PGADMIN_CONFIG_STORAGE_DIR: "'/var/lib/pgadmin/storage'"
      PGADMIN_CONFIG_FILE_MANAGER_STORAGE_PATH: "'/var/lib/pgadmin/storage'"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
      PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD: "False"
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: "5"
      PGADMIN_CONFIG_X_FRAME_OPTIONS: "'SAMEORIGIN'"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./data/pgadmin/servers.json:/pgadmin4/servers.json:ro
    restart: always
    ports:
      - "8035:80"

volumes:
  postgres_data:
    name: infra_kit_postgres_data
  redis_data:
    name: infra_kit_redis_data
  rabbitmq_data:
    name: infra_kit_rabbitmq_data
  pgadmin_data:
    name: infra_kit_pgadmin_data
